// Reads CEF version from cef_version.h and writes a TS constant file.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dirname, "..");
const headerPaths = [
  join(root, "vendors", "cef", "include", "cef_version.h"),
  join(root, "native-build", "win-x64", "cef", "include", "cef_version.h"),
];

let header = "";
for (const p of headerPaths) {
  try { header = readFileSync(p, "utf8"); break; } catch {}
}
if (!header) {
  console.error("cef_version.h not found");
  process.exit(1);
}

const major = header.match(/CEF_VERSION_MAJOR\s+(\d+)/)?.[1];
const minor = header.match(/CEF_VERSION_MINOR\s+(\d+)/)?.[1];
const patch = header.match(/CEF_VERSION_PATCH\s+(\d+)/)?.[1];

if (!major || !minor || !patch) {
  console.error("Failed to parse CEF version from header");
  process.exit(1);
}

const version = `${major}.${minor}.${patch}`;
const outPath = join(root, "src", "shared", "cefVersion.ts");
writeFileSync(outPath, `// Auto-generated by scripts/gen-cef-version.ts\nexport const CEF_VERSION = "${version}";\n`);
console.log(`CEF_VERSION = ${version} → ${outPath}`);
